name: 🐛 Bug Report
description: File a bug report
title: '[🐛 Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for taking the time to fill out this bug report!

        Before creating the issue please make sure that:

         - There isn't already an existing issue covering the same bug, if there is, please add a comment there instead.

         - If the issue concerns a missing Next.js feature, such is not already present in our [Supported Versions and Features document](https://github.com/fleek-platform/next-on-fleek/blob/main/packages/next-on-fleek/docs/supported.md).

        > ℹ️ Please try to provide as much details as you can, the more details you can include the more likely it is for the issue to get quickly addressed.

  - type: textarea
    id: next-on-fleek-info
    attributes:
      label: next-on-fleek environment related information
      description: What output do you get when running `npx @fleek-platform/next-on-fleek --info`?
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Please provide a detailed way of reproducing the bug.
        > ⚠️ Important Note:
        >    Providing a GitHub repository that can present the bug is usually by far the most helpful thing that an issue can supply
        >    please try to provide one if you can as that will likely help addressing the issue much much quicker.
    validations:
      required: false

  - type: dropdown
    id: fleek-functions-deployment-method
    attributes:
      label: Fleek Functions Deployment Method
      description: If you have have deployed (or tried to deploy) your application, what method have you used?
      options:
        - Fleek CLI (`@fleek-platform/cli`)
        - Fleek Next CLI (`@fleek-platform/fleek-next`)

  - type: input
    id: fleek-function-slug
    attributes:
      label: Fleek Function Slug
      description: If you have have a Function slug where you reproduced this bug, this may additionally help us to debug the problem.
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Is there anything else you'd like to add?
    validations:
      required: false

  - type: checkboxes
    id: help
    attributes:
      label: Would you like to help?
      options:
        - label: Would you like to help fixing this bug?
