name: Pull request checks

on:
  pull_request:
  push:
    branches:
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  simple-checks:
    strategy:
      matrix:
        check:
          [
            { name: formatting, script: 'prettier:check' },
            { name: linting, script: lint },
            { name: type checking, script: types-check },
            { name: building, script: build },
            { name: unit testing, script: 'test:unit' },
          ]
    name: ${{ matrix.check.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/node-setup

      - name: Cache Turbo
        uses: ./.github/actions/cache-turbo
        with:
          script: ${{ matrix.check.script }}

      - name: Run Script
        run: npm run ${{ matrix.check.script }} -- --cache-dir ./turbo-cache
